### ISSUE TITLE
Save the Dataset via Python Variables

### ISSUE THREAD

**Issue by thejjserg** [Data-Science-and-Analysts-Projects/us-medical-insurance#5]
Description from Codecademy
Save the features of your dataset (the columns) from insurance.csv by storing them in variables that can be used for analysis. As you consider what types of variables to use and how many you plan to create, think ahead about the parameters you wish to investigate and how your organization will impact this analysis.

You may need to use another library to store information from insurance.csv into Python variables. One helpful csv method could be [DictReader()](https://docs.python.org/3/library/csv.html#csv.DictReader). The Python documentation will show examples of using the method. Using this method, you can iterate through rows of the dataset and store columns in specific lists or dictionaries that will be incredibly useful for analysis.

**Comment by GALLP900** [comment]
@thejjserg closing issue since this is completed
